#!/usr/bin/env bash

# run
# Run command with timeout $1.

max_timeout="$1"
shift

# PID
pid=$$

# Start timeout
(
  sleep "$max_timeout"
  echo "Timed out after $max_timeout"
  kill -- -$pid &>/dev/null
) &
timeout_pid=$!

# Run
"$@"

# Stop timeout
kill $timeout_pid &>/dev/null